const Product_data = [
  {
    id: 1,
    title: "Wholesale Nike Air Max 90",
    price: 10.99,
    image: "/product1.png",
    category:"Electronics",
  },
  {
    id: 2,
    title: "Wholesale Apple iPhone 12 Pro",
    price: 19.99,
    image: "/product1.png",
    category:"Stationary",
  },
  {
    id: 3,
    title: "Wholesale Samsung Galaxy Watch 4",
    price: 14.99,
    image: "/product1.png",
    category:"Cosmetics",
  },
  {
    id: 4,
    title: "Wholesale Sony PlayStation 5",
    price: 14.99,
    image: "/product1.png",
    category:"KitchenWare",
  },
  {
    id: 5,
    title: "Wholesale Canon EOS R5 Mirrorless Camera",
    price: 14.99,
    image: "/product1.png",
    category:"Beverages",
  },
  {
    id: 6,
    title: "Wholesale Beats Studio3 Wireless Headphones",
    price: 14.99,
    image: "/product1.png",
    category:"Food and Grocery",
  },
  {
    id: 7,
    title: "Wholesale KitchenAid Stand Mixer",
    price: 14.99,
    image: "/product1.png",
    category:"Electronics",
  },
  {
    id: 8,
    title: "Wholesale Dyson V11 Absolute Vacuum Cleaner",
    price: 14.99,
    image: "/product1.png",
    category:"Electronics",
  },
  {
    id: 9,
    title: "Wholesale Dyson V11 Absolute Vacuum Cleaner",
    price: 14.99,
    image: "/product1.png",
    category:"Electronics",
  },
  {
    id: 10,
    title: "Wholesale Dyson V11 Absolute Vacuum Cleaner",
    price: 14.99,
    image: "/product1.png",
    category:"Electronics",
  },
  {
    id: 11,
    title: "Wholesale Dyson V11 Absolute Vacuum Cleaner",
    price: 14.99,
    image: "/product1.png",
    category:"Electronics",
  },
  {
    id: 12,
    title: "Wholesale Dyson V11 Absolute Vacuum Cleaner",
    price: 14.99,
    image: "/product1.png",
    category:"Electronics",
  },
  {
    id: 13,
    title: "Wholesale Dyson V11 Absolute Vacuum Cleaner",
    price: 14.99,
    image: "/product1.png",
    category:"Electronics",
  },
  {
    id: 14,
    title: "Wholesale Dyson V11 Absolute Vacuum Cleaner",
    price: 14.99,
    image: "/product1.png",
    category:"Electronics",
  },
  {
    id: 15,
    title: "Wholesale Dyson V11 Absolute Vacuum Cleaner",
    price: 14.99,
    image: "/product1.png",
    category:"Electronics",
  },
  {
    id: 16,
    title: "Wholesale Dyson V11 Absolute Vacuum Cleaner",
    price: 14.99,
    image: "/product1.png",
    category:"Electronics",
  },
  {
    id: 17,
    title: "Wholesale Dyson V11 Absolute Vacuum Cleaner",
    price: 14.99,
    image: "/product1.png",
    category:"Electronics",
  },
  {
    id: 18,
    title: "Wholesale Dyson V11 Absolute Vacuum Cleaner",
    price: 14.99,
    image: "/product1.png",
    category:"Electronics",
  },
  {
    id: 19,
    title: "Wholesale Dyson V11 Absolute Vacuum Cleaner",
    price: 14.99,
    image: "/product1.png",
    category:"Electronics",
  },
  {
    id: 20,
    title: "Wholesale Dyson V11 Absolute Vacuum Cleaner",
    price: 14.99,
    image: "/product1.png",
    category:"Electronics",
  },

];

export default Product_data;
